const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bioText(t){return t.replace(/XD/g,'Xᴰ').replace(/A([12])/g,(_,n)=>'A'+('₁₂'[+n-1])).replace(/F([12])/g,(_,n)=>'F'+('₁₂'[+n-1])).replace(/([ⅠⅡⅢ])([1-9])/g,(_,r,n)=>r+'₀₁₂₃₄₅₆₇₈₉'[+n])}
const key='biology-five-v1';let state;try{state=JSON.parse(localStorage.getItem(key))}catch{}state=state&&state.version===1?state:{version:1,q:0,answers:{},passed:{},open:{},times:[0,0,0,0,0]};state.submitted={...state.passed,...(state.submitted||{})};let paused=false;const save=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}};
const titles=['分裂时期与基因分离','互换能改变什么','从精细胞推算交换比例','PCR 与电泳条带','系谱图中的条件概率'];
function opts(q){return QUESTIONS[q].content.flatMap(c=>c.text.split(/\t+/)).filter(t=>/^[ABCD]．/.test(t)&&t.length>2).map(t=>t.replace(/^[ABCD]．/,''))}
const steps=[
[{id:'q1',name:'据图分析，选择正确的叙述',type:'choice',options:opts(0),answer:'C',lessons:[0,1,2]}],
[{id:'q2',name:'哪幅细胞分裂图不可能出现？',type:'choice',options:['图 A','图 B','图 C','图 D'],answer:'B',lessons:[3,4,5]}],
[{id:'q3',name:'发生交换的初级精母细胞占多少？',type:'choice',options:['2%','4%','8%','16%'],answer:'D',lessons:[6,7,8]}],
[{id:'q4a',name:'(1) 紧凑株型由哪个基因控制？',type:'input',answer:'a',placeholder:'输入 A 或 a（区分大小写）',lessons:[9],hint:'F₁全为松散株型；F₂表现为3∶1。紧凑株型是隐性性状，由小写 a 控制。'},
{id:'q4b',name:'(2) 插入序列后，肽链为什么反而变短？',type:'choice',options:['DNA 变长，翻译速度就会减慢','终止密码子提前出现，翻译提前结束','所有插入突变都会让转录停止'],answer:'B',lessons:[],hint:'肽链长度取决于翻译何时结束。插入可能使终止密码子提前出现，导致翻译提前终止；不是说所有插入都会让肽链变短。'},
{id:'q4c',name:'(3) ① 图2-A使用哪组引物？',type:'choice',options:['P1 和 P2','P1 和 P3','P2 和 P3'],answer:'C',lessons:[10]},
{id:'q4d',name:'(3) ① 丙为什么没有扩增条带？',type:'choice',options:['丙为 AA，缺少 P3 的结合序列','丙没有 DNA','丙为 aa，插入片段太长'],answer:'A',lessons:[10]},
{id:'q4e',name:'(3) ② 点选乙和丙应有的电泳条带',type:'gel',answer:'1001',lessons:[11]},
{id:'q4f',name:'(3) ③ 有条带松散株∶无条带松散株 = ？',type:'input',answer:'2:1',placeholder:'例如 3:1',lessons:[12]}],
[{id:'q5',name:'结合系谱图与电泳结果，选择正确叙述',type:'choice',options:opts(4),answer:'B',lessons:[13,14,15,16]}]
];
// Each scored step is unique; reviewing explanations never awards points.
function notify(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2300)}
function renderSummary(){let n=Object.keys(state.passed).filter(k=>state.passed[k]).length;$('#score').innerHTML=n*20+' <small>/ 200</small>';$('#meter').style.width=n*10+'%';$('#badge').textContent=n===10?'5题全部完成！已获得「遗传小导师」勋章。':n>=5?'已获得「推理达人」，继续向满分前进。':n>=1?'已点亮「探索之星」，继续加油。':'每掌握一步，都有新的进步。';$('#badges').innerHTML=[['★',1,'探索之星'],['✦',5,'推理达人'],['♛',10,'遗传小导师']].map(([s,min,t])=>`<span title="${t}" aria-label="${t}${n>=min?' 已获得':' 未获得'}" class="${n>=min?'':'off'}">${s}</span>`).join('');$('#nav').innerHTML=titles.map((t,i)=>{const done=steps[i].filter(s=>state.passed[s.id]).length;const completed=done===steps[i].length;const started=steps[i].some(s=>state.submitted[s.id]);const status=completed?'已完成':started?'作答中':'待作答';return `<button class="navitem ${i===state.q?'active':''} ${completed?'finished':''}" aria-current="${i===state.q?'step':'false'}" aria-label="第${i+1}题，${t}，${status}" data-q="${i}"><b>第${i+1}题</b><span class="nav-status">${status}</span></button>`}).join('');$('#done').textContent=steps[state.q].filter(s=>state.passed[s.id]).length+' / '+steps[state.q].length+' 步';$('#finish').innerHTML=n===10?'<div class="complete"><h2>♛ 五题通关 · 遗传小导师</h2><p>你已获得 200 分。可以返回任意题，重新听一遍老师的推理过程。</p></div>':''}
function figure(file,label){return `<div class="figures"><img src="${file}" alt="${esc(label)}"></div>`}
function stepContext(s){const c=QUESTIONS[3].content;if(s.id==='q4b')return `<p class="step-context">${esc(bioText(c[2].text.replace(/^\(2\)/,'').split('造成此现象')[0]))}</p>${figure(c[3].images[0],'图1：基因插入片段与引物位置')}`;if(s.id==='q4c')return `<p class="step-context">${esc(bioText(c[4].text))}</p>${figure(c[5].images[0],'图2：甲乙丙的电泳结果')}`;if(s.id==='q4e')return figure(c[5].images[0],'参照原图补充乙和丙的条带');return ''}
function stepBody(s,i){const unlocked=!!state.submitted[s.id];return `${stepContext(s)}<h3>${state.q===3?`<small>第 ${i+1} 步</small>`:''}${s.name}</h3>${controls(s)}<div class="actions"><button data-check="${s.id}">${unlocked?'再次提交':'提交答案'}</button><button class="hintbutton" data-explain="${s.id}" ${unlocked?'':'disabled'} aria-expanded="${unlocked&&!!state.open[s.id]}">${unlocked?(state.open[s.id]?'收起解析':'查看分步解析'):'提交后可看解析'}</button></div><div class="result" role="status">${state.passed[s.id]?'<div class="feedback good">✓ 这一步已答对 · 20 分已计入</div>':''}</div><div class="explanation">${unlocked&&state.open[s.id]?explain(s):''}</div>`}
function renderKnowledge(){const ready=steps[state.q].every(s=>state.submitted[s.id]);$('#knowledge').innerHTML=ready?knowledgeCard(state.q):'<p class="knowledge-locked">完成本题作答后，解锁课本知识联动。</p>'}
function render(){paused=false;$('#pause').textContent='暂停计时';document.querySelectorAll('audio').forEach(a=>a.pause());const q=QUESTIONS[state.q];$('#chapter').textContent=q.chapter;$('#title').textContent='第'+(state.q+1)+'题 · '+titles[state.q];$('#counter').textContent=state.q===3?'综合题 · 6个步骤':'单项选择题';const before=q.content.slice(0,q.content.findIndex(c=>c.text.startsWith('【答案】')));$('#question').innerHTML=(state.q===3?before.slice(0,1):before).map(c=>{if(/^[ABCD]．/.test(c.text))return '';return (c.text?`<p>${esc(bioText(c.text))}</p>`:'')+c.images.map(img=>figure(img,'第'+q.number+'题原题图')).join('')}).join('');$('#steps').innerHTML=steps[state.q].map((s,i)=>`<article class="step" id="step-${s.id}">${stepBody(s,i)}</article>`).join('');renderKnowledge();$('#prev').disabled=state.q===0;$('#next').disabled=state.q===4;renderSummary();renderClock();save()}
const AUDIO_FILES={"q1-0": "q1-0-v4b.mp3", "q1-1": "q1-1-v4.mp3", "q1-2": "q1-2-v4.mp3", "concept-division": "concept-division-v4.mp3", "concept-count": "concept-count-v4.mp3", "concept-segregation": "concept-segregation-v4.mp3"};
function voicePlayer(id,label='听老师讲解'){const filename=AUDIO_FILES[id]||id+'-v3.mp3';return `<div class="teacher-audio"><div><span class="teacher-mark">声</span><b>${label}</b><small>老师声音 · 轻快版</small></div><audio controls preload="none" src="audio/${filename}" aria-label="${label}"></audio></div>`}
function conceptCard(id){const c=CONCEPTS[id];return `<details class="linked-concept"><summary><span>关联知识</span><b>${esc(c[0])}</b><em>点击展开 ＋</em></summary><div class="concept-body">${voicePlayer('concept-'+id,'听老师讲这个知识点')}<h5>概念是什么</h5><p>${esc(c[1])}</p><h5>如何理解和应用</h5><p>${esc(c[2])}</p><div class="concept-takeaway">记住：${esc(c[3])}</div></div></details>`}
function optionCard(s,i){const c=OPTION_INSIGHTS[s.id]?.[i],d=DEEP_OPTIONS[s.id]?.[i];if(!c||!d)return '';const correct='ABCD'[i]===s.answer;return `<details class="option-card"><summary><span>${correct?'✓ 正确选项':'辨析 '+ 'ABCD'[i]}</span>${esc(c[0])}</summary><div class="option-card-body">${voicePlayer(s.id+'-'+i,'听老师解析选项'+ 'ABCD'[i])}<div class="reasoning-chain">${['题目依据','推理过程','得出结论'].map((t,j)=>`<section><h5><span>${j+1}</span>${t}</h5><p>${esc(d[j])}</p></section>`).join('')}</div>${conceptCard(d[3])}</div></details>`}
function controls(s){const a=state.answers[s.id];if(s.type==='choice')return '<div class="options">'+s.options.map((o,i)=>`<div class="option-wrap"><button class="option ${a==='ABCD'[i]?'selected':''}" data-answer="${s.id}" data-value="${'ABCD'[i]}" aria-pressed="${a==='ABCD'[i]}"><b>${'ABCD'[i]}</b><span>${esc(bioText(o))}${s.id==='q2'?`<img class="option-diagram" src="${QUESTIONS[1].content[1].images[i]}" alt="选项${'ABCD'[i]}细胞分裂图">`:''}</span></button>${state.submitted[s.id]?`<div class="option-notes">${optionCard(s,i)}</div>`:''}</div>`).join('')+'</div>';if(s.type==='input')return `<div class="inputwrap"><input type="text" data-input="${s.id}" value="${esc(a||'')}" placeholder="${s.placeholder}" aria-label="${esc(s.name)}" autocomplete="off"></div>`;return `<p class="gelkey">上方＝长片段，靠近点样孔；下方＝短片段。点击条带位置涂黑或取消。</p><div class="gel"><div class="lane"><span>甲（参照）</span><span class="band on">━━</span><span class="band on">━━</span></div>${['乙','丙'].map((label,k)=>`<div class="lane"><span>${label}</span>${[0,1].map(j=>`<button class="band ${(a||'0000')[k*2+j]==='1'?'on':''}" data-band="${s.id}" data-index="${k*2+j}" aria-label="${label}${j?'下':'上'}条带" aria-pressed="${(a||'0000')[k*2+j]==='1'}">${(a||'0000')[k*2+j]==='1'?'━━':'＋'}</button>`).join('')}</div>`).join('')}</div>`}
function knowledgeCard(q){const ids=[['division','count','segregation','gametes'],['recombination','segregation'],['ratio'],['segregation','expression','pcr','electrophoresis'],['alleles','conditional']][q];return `<details class="knowledge-card"><summary><span class="book-icon">书</span><span><small>课本知识联动</small><b>本题涉及的 ${ids.length} 个知识点</b></span><span class="expand-label">点击查看 ＋</span></summary><div class="knowledge-body"><p class="muted">选择需要复习的概念，再展开阅读或听讲解。</p>${ids.map(conceptCard).join('')}<small class="muted">按高中生物课程知识主题整理；不对应某一教材版本的固定页码。</small></div></details>`}
function explain(s){if(DEEP_OPTIONS[s.id])return `<div class="explain"><h4>逐项辨析 · 选择一个选项听老师讲解</h4>${DEEP_OPTIONS[s.id].map((_,i)=>optionCard(s,i)).join('')}</div>`;if(DEEP_STEPS[s.id]){const d=DEEP_STEPS[s.id];return `<div class="explain">${voicePlayer('step-'+s.id,'听老师讲这一步')}<div class="reasoning-chain">${['题目依据','推理过程','得出结论'].map((t,j)=>`<section><h5>${t}</h5><p>${esc(d[j])}</p></section>`).join('')}</div>${conceptCard(d[3])}</div>`}let list=s.lessons;if(s.id==='q4b')list=[9];return (s.hint?`<div class="explain"><h4>推理提示</h4><p>${esc(s.hint)}</p></div>`:'')+list.map(i=>{const l=LESSONS[i];return `<div class="explain"><h4>${esc(l.heading)}</h4><div class="formula">${esc(l.formula)}</div><ul>${l.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul><div class="voice-label">老师声音讲解 · 轻快版 · 点击播放</div><audio controls preload="none" src="${l.file}"></audio><details><summary>查看讲解文字</summary><p>${esc(l.voice)}</p></details></div>`}).join('')}
function findStep(id){return steps.flat().find(s=>s.id===id)}
function check(id){const s=findStep(id),raw=state.answers[id]||'';if(!raw.trim()||(s.type==='gel'&&raw==='0000')){notify('先填写或点选你的答案');return}let a=raw.trim();if(s.id==='q4f')a=a.replace(/[：∶／/]/g,':').replace(/\s/g,'');let good=a===s.answer;const already=!!state.passed[id];state.submitted[id]=true;if(good&&!already){state.passed[id]=true;notify('★ +20 分 · 又掌握了一个知识点')}save();document.querySelectorAll('#step-'+id+' audio').forEach(a=>a.pause());$('#step-'+id).innerHTML=stepBody(s,steps[state.q].indexOf(s));$('#step-'+id+' .result').innerHTML=`<div class="feedback ${good?'good':'bad'}">${good?'✓ 答对了！'+(already?'本步骤已得分，不重复计分。':' +20 分，继续保持！'):'答案还不正确，解析已解锁。看看推理过程，再试一次；答错不扣分。'}</div>`;renderKnowledge();renderSummary()}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-q]');if(b){state.q=+b.dataset.q;render();window.scrollTo({top:0,behavior:'smooth'})}});
$('#steps').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.answer){state.answers[b.dataset.answer]=b.dataset.value;$('#step-'+b.dataset.answer).querySelectorAll('[data-answer]').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',n===b)});$('#step-'+b.dataset.answer+' .result').innerHTML='';save()}if(b.dataset.band){let a=(state.answers[b.dataset.band]||'0000').split('');a[+b.dataset.index]=a[+b.dataset.index]==='1'?'0':'1';state.answers[b.dataset.band]=a.join('');b.classList.toggle('on',a[+b.dataset.index]==='1');b.textContent=a[+b.dataset.index]==='1'?'━━':'＋';b.setAttribute('aria-pressed',a[+b.dataset.index]==='1');save()}if(b.dataset.check)check(b.dataset.check);if(b.dataset.explain){let id=b.dataset.explain;if(!state.submitted[id])return;state.open[id]=!state.open[id];$('#step-'+id+' .explanation').innerHTML=state.open[id]?explain(findStep(id)):'';b.textContent=state.open[id]?'收起解析':'查看分步解析';b.setAttribute('aria-expanded',!!state.open[id]);save()}});
$('#steps').addEventListener('input',e=>{if(e.target.dataset.input){state.answers[e.target.dataset.input]=e.target.value;save()}});$('#steps').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.dataset.input)check(e.target.dataset.input)});
document.addEventListener('toggle',e=>{if(e.target.tagName==='DETAILS'&&!e.target.open)e.target.querySelectorAll('audio').forEach(a=>a.pause())},true);
document.addEventListener('play',e=>{if(e.target.tagName==='AUDIO')document.querySelectorAll('audio').forEach(a=>{if(a!==e.target)a.pause()})},true);document.addEventListener('error',e=>{if(e.target.tagName==='AUDIO')notify('音频暂时无法播放，请先阅读下方讲解文字。')},true);
function move(n){state.q=Math.max(0,Math.min(4,state.q+n));render();window.scrollTo({top:0,behavior:'smooth'})}$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'继续计时':'暂停计时'};
function renderClock(){let t=state.times[state.q]||0;$('#clock').textContent=`学习计时 ${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`}
setInterval(()=>{if(!paused&&!document.hidden){state.times[state.q]++;renderClock();save()}},1000);$('#reset').onclick=()=>$('#resetdialog').showModal();$('#cancelreset').onclick=()=>$('#resetdialog').close();$('#confirmreset').onclick=()=>{state={version:1,q:0,answers:{},passed:{},open:{},submitted:{},times:[0,0,0,0,0]};paused=false;$('#pause').textContent='暂停计时';$('#resetdialog').close();save();render()};
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'navigate_biology_question',description:'打开前五道生物练习中的指定题目，不提交答案。',inputSchema:{type:'object',properties:{number:{type:'integer',minimum:1,maximum:5}},required:['number'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({number})=>{if(!Number.isInteger(number)||number<1||number>5)throw Error('题号须为1至5');state.q=number-1;render();return {question:number,title:titles[state.q]}}})}
render();
